version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user $SURREAL_DB_USER --pass $SURREAL_DB_PASSWORD memory
    ports:
      - 8000:8000

